config/routes.rb
  SampleApp::Application.routes.draw do

 
  get "sessions/new"

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  resources :users do
      collection do
      get :tigers
    end
  end  

  match '/signup', :to => 'users#new'

  match '/signin', :to => 'sessions#new'

  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'

  match '/about', :to => 'pages#about'

  match '/help', :to => 'pages#help'
  
  match '/home', :to => 'pages#home'

  root :to => 'pages#home'

end

app/models/user.rb
# == Schema Information
# Schema version: <timestamp>
#
# Table name: users
#
# id :integer not null, primary key
# name :string(255)
# email :string(255)
# created_at :datetime
# updated_at :datetime
#
	


require 'digest'
class User < ActiveRecord::Base

	attr_accessor :password
	attr_accessible :name, :email, :password, :password_confirmation

	has_many :microposts, :dependent => :destroy

	has_many :relationships, :foreign_key => "follower_id", :dependent => :destroy
	has_many :following, :through => :relationships, :source => :followed

	has_many :reverse_relationships, :foreign_key => "followed_id", :class_name => "Relationship",
             :dependent => :destroy
    has_many :followers, :through => :reverse_relationships, :source => :follower

	validates :name, :presence => true, :length => { :maximum => 50 }
	validates :email, :presence => true, :uniqueness =>  { :case_sensitive => false }
	validates :password, :presence => true, :confirmation => true, :length => { :within => 6..40 }

	before_save :encrypt_password
	

	def has_password?(submitted_password)
		encrypted_password == encrypt(submitted_password)
	end

	def self.authenticate(email, submitted_password)
		user = find_by_email(email)
		return nil if user.nil?
		return user if user.has_password?(submitted_password)
	end

	def self.authenticate_with_salt(id, cookie_salt)
		user = find_by_id(id)
		(user && user.salt == cookie_salt) ? user : nil
	end
	
	def feed
		# This is preliminary. See Chapter 12 for the full implementation.
		Micropost.from_users_followed_by(self)
	end
	
	def following?(followed)
		relationships.find_by_followed_id(followed)
	end

	def follow!(followed)
		relationships.create!(:followed_id => followed.id)
	end

	def unfollow!(followed)
		relationships.find_by_followed_id(followed).destroy
	end

	private

		def encrypt_password
			self.salt = make_salt if new_record?

			self.encrypted_password = encrypt(password)
		end

		def make_salt
			secure_hash("#{Time.now.utc}--#{password}")
		end

		def encrypt(string)
			secure_hash("#{salt}--#{string}")	
		end

		def secure_hash(string)
			Digest::SHA2.hexdigest(string)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate, :only => [:index, :edit, :update]
  before_filter :correct_user, :only => [:edit, :update]
  # before_filter :admin_user, :only => :destroy

  def new
	@user = User.new
	@title = "Sign up"
  end

  def show
	@user = User.find(params[:id])
	@microposts = @user.microposts.paginate(:page => params[:page])
	@title = @user.name
  end

  def create
	@user = User.new(params[:user])
		if @user.save
		# Handle a successful save.

			puts("*********************");
			puts("*********************");
			puts("*********************");
			puts("*********************");
			puts("*********************");
			puts("sign up sssuuccceesssssfffuuuulllll");
			puts("*********************");
			puts("*********************");
		
			sign_in @user
			flash[:success] = "Welcome to the Sample App!"
			redirect_to @user
		else
			puts("*********************");
			puts("*********************");
			puts("*********************");
			puts("*********************");
			puts("*********************");
			puts("sign up fail");
			puts("*********************");
			puts("*********************");
		
			@title = "Sign up"
			render 'new'
		end
	end

	def edit
		@user = User.find(params[:id])
		@title = "Edit user"
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(params[:user])
			flash[:success] = "Profile updated."
			redirect_to @user
		else
			@title = "Edit user"
			render 'edit'
		end
	end

	def index
		@title = "All users"
		@users = User.paginate(:page => params[:page])
	end

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "User destroyed."
		redirect_to users_path
	end


	def following
		@title = "Following"
		@user = User.find(params[:id])
		@users = @user.following.paginate(:page => params[:page])
		render 'show_follow'
	end

	def followers
		@title = "Followers"
		@user = User.find(params[:id])
		@users = @user.followers.paginate(:page => params[:page])
		render 'show_follow'
	end

	private


		def correct_user
			@user = User.find(params[:id])
			redirect_to(root_path) unless current_user?(@user)
		end

		def admin_user
			redirect_to(root_path) unless current_user.admin?
		end

end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, options = { :size => 50 })
		gravatar_image_tag(user.email.downcase, :alt => user.name,
		:class => 'gravatar',
		:gravatar => options)
	end
end

app/views/users/_follow.html.erb
<%= form_for current_user.relationships.
	build(:followed_id => @user.id), :remote => true do |f| %>
		<div><%= f.hidden_field :followed_id %></div>
		<div class="actions"><%= f.submit "Follow" %></div>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
	<div id="follow_form">
		<% if current_user.following?(@user) %>
			<%= render 'unfollow' %>
		<% else %>
			<%= render 'follow' %>
		<% end %>
	</div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for current_user.relationships.find_by_followed_id(@user),
	:html => { :method => :delete }, :remote => true do |f| %>
	<div class="actions"><%= f.submit "Unfollow" %></div>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, :size => 30 %>
	<%= link_to user.name, user %>

	<% if current_user.admin? %>
	<%= button_to "delete", user, :method => :delete, :confirm => 'are you sure?',  :title => "Delete #{user.name}" %>
	<% end %>
		
</li>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>

	<div class="field">
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</div>

	<div class="field">
		<%= f.label :password_confirmation, "Confirmation" %><br />
		<%= f.password_field :password_confirmation %>
	</div>

	<div class="actions">
		<%= f.submit "Update" %>
	</div>

<% end %>


<div>
	<%= gravatar_for @user %>
	<a href="http://gravatar.com/emails">change</a>
</div>

app/views/users/index.html.erb
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>

	<%= render 'shared/error_messages' %>

	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>

	<div class="field">
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</div>

	<div class="field">
		<%= f.label :password_confirmation, "Confirmation" %><br />
		<%= f.password_field :password_confirmation %>
	</div>
	
	<div class="actions">
		<%= f.submit "Sign up" %>
	</div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
	<tr>
		<td class="main">
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
			<%= render 'follow_form' if signed_in? %>
			<% unless @user.microposts.empty? %>
				<table class="microposts" summary="User microposts">
					<%= render @microposts %>
				</table>
				<%= will_paginate @microposts %>
			<% end %>

		</td>
		<td class="sidebar round">
			<strong>Name</strong> <%= @user.name %><br />
			<strong>URL</strong> <%= link_to user_url(@user), @user %>
			<strong>Microposts</strong> <%= @user.microposts.count %>
			<%= render 'shared/stats' %>
			<%= link_to "delete", user_url(@user), :method => 'delete', :title => "Delete #{@user.name}" %>
		</td>
	</tr>
</table>

app/views/users/show_follow.html.erb
<table summary="Information about following/followers">
	<tr>
		<td class="main">
			<h1><%= @title %></h1>
			<% unless @users.empty? %>

				<ul class="users">
				<%= render @users %>
				</ul>

				<%= will_paginate @users %>
			<% end %>
		</td>

		<td class="sidebar round">
			<strong>Name</strong> <%= @user.name %><br />
			<strong>URL</strong> <%= link_to user_path(@user), @user %><br />
			<strong>Microposts</strong> <%= @user.microposts.count %>
			
			<%= render 'shared/stats' %>
			
			<% unless @users.empty? %>
				<% @users.each do |user| %>
					<%= link_to gravatar_for(user, :size => 30), user %>
				<% end %>
			<% end %>
		</td>
	</tr>
</table>